### PR TITLE
thermal radiation sanity adjustments

### PR DESCRIPTION
**Pull request by Starwaster**
Adjusted emissivity value for several problematic planets (Jupiter, gas giants et all and possibly Venus)

### CODE REVIEW

**Comment by Starwaster** [comment]
Dammit, did not rebase first

**Comment by NathanKell** [comment]
Wrong repo too. KSP-RO one is the right one. I should close this somehow

Sent by my thumbs, slowly.

**Comment by Starwaster** [comment]
It's already closed :P 
(also, the reason I thought I hadn't rebased was _because_ I was sending it to the wrong repo.... probably proving one should not send pull requests when one has a fever)

**Comment by NathanKell** [comment]
No I mean close this repo, not your issue. I saw you posted it on the right
one. Sorry I wasn't clearer, phone typing ftw. Hope you're feeling better!

**Pull request closed without merging**
